require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PodsController do

  # This should return the minimal set of attributes required to create a valid
  # Pod. As you add validations to Pod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pods as @pods" do
      pod = Pod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pods).should eq([pod])
    end
  end

  describe "GET show" do
    it "assigns the requested pod as @pod" do
      pod = Pod.create! valid_attributes
      get :show, {:id => pod.to_param}, valid_session
      assigns(:pod).should eq(pod)
    end
  end

  describe "GET new" do
    it "assigns a new pod as @pod" do
      get :new, {}, valid_session
      assigns(:pod).should be_a_new(Pod)
    end
  end

  describe "GET edit" do
    it "assigns the requested pod as @pod" do
      pod = Pod.create! valid_attributes
      get :edit, {:id => pod.to_param}, valid_session
      assigns(:pod).should eq(pod)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pod" do
        expect {
          post :create, {:pod => valid_attributes}, valid_session
        }.to change(Pod, :count).by(1)
      end

      it "assigns a newly created pod as @pod" do
        post :create, {:pod => valid_attributes}, valid_session
        assigns(:pod).should be_a(Pod)
        assigns(:pod).should be_persisted
      end

      it "redirects to the created pod" do
        post :create, {:pod => valid_attributes}, valid_session
        response.should redirect_to(Pod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pod as @pod" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pod.any_instance.stub(:save).and_return(false)
        post :create, {:pod => {  }}, valid_session
        assigns(:pod).should be_a_new(Pod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pod.any_instance.stub(:save).and_return(false)
        post :create, {:pod => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pod" do
        pod = Pod.create! valid_attributes
        # Assuming there are no other pods in the database, this
        # specifies that the Pod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pod.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => pod.to_param, :pod => { "these" => "params" }}, valid_session
      end

      it "assigns the requested pod as @pod" do
        pod = Pod.create! valid_attributes
        put :update, {:id => pod.to_param, :pod => valid_attributes}, valid_session
        assigns(:pod).should eq(pod)
      end

      it "redirects to the pod" do
        pod = Pod.create! valid_attributes
        put :update, {:id => pod.to_param, :pod => valid_attributes}, valid_session
        response.should redirect_to(pod)
      end
    end

    describe "with invalid params" do
      it "assigns the pod as @pod" do
        pod = Pod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pod.any_instance.stub(:save).and_return(false)
        put :update, {:id => pod.to_param, :pod => {  }}, valid_session
        assigns(:pod).should eq(pod)
      end

      it "re-renders the 'edit' template" do
        pod = Pod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pod.any_instance.stub(:save).and_return(false)
        put :update, {:id => pod.to_param, :pod => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pod" do
      pod = Pod.create! valid_attributes
      expect {
        delete :destroy, {:id => pod.to_param}, valid_session
      }.to change(Pod, :count).by(-1)
    end

    it "redirects to the pods list" do
      pod = Pod.create! valid_attributes
      delete :destroy, {:id => pod.to_param}, valid_session
      response.should redirect_to(pods_url)
    end
  end

end
